<a href="https://colab.research.google.com/github/katyk20/DistanceLearning_Capstone/blob/main/Code%20Notebooks/NCES_IPEDS_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [44]:
# ! git clone https://github.com/katyk20/DistanceLearning_Capstone

In [45]:
# %cd /content/DistanceLearning_Capstone
# !git pull

In [46]:
#Libraries
import pandas as pd
import os
import glob

In [47]:
# #ef2022a file to large to upload to GitHub- split+ concat
# #insert into dictionary below

# # ef2022a_1=pd.read_csv('/content/DistanceLearning_Capstone/NCES IPEDS Data 2019-2022/ef2022a_1.csv')
# # ef2022_a2=pd.read_csv('/content/DistanceLearning_Capstone/NCES IPEDS Data 2019-2022/ef2022a_2.csv')
# # ef2022a= pd.concat([ef2022a_1, ef2022_a2], ignore_index=True)
# # ef2022a.to_csv('ef2022a.csv', index=False)



# def combine_csv_files(file_path1,file_path2, output_file_name):
#     df1 = pd.read_csv(file_path1)
#     df2 = pd.read_csv(file_path2)
#     combined_df= pd.concat([df1, df2], ignore_index=True)

#     # Write the combined DataFrame to a new CSV file
#     return combined_df.to_csv(output_file_name, index=False)

In [48]:
# #ef2022a file to large to upload to GitHub- split+ concat
# #insert into dictionary below
# file_path1 = '/content/DistanceLearning_Capstone/NCES IPEDS Data 2019-2022/ef2022a_1.csv'
# file_path2='/content/DistanceLearning_Capstone/NCES IPEDS Data 2019-2022/ef2022a_2.csv'
# output_file_name = 'ef2022a.csv'
# combine_csv_files(file_path1,file_path2, output_file_name)

In [49]:
# #ef2018a file to large to upload to GitHub- split+ concat
# #insert into dictionary belowfile_path1 = '/content/DistanceLearning_Capstone/NCES IPEDS Data 2019-2022'
# file_path1= '/content/DistanceLearning_Capstone/NCES IPEDS Data 2019-2022/ef2018a_rv_1.csv'
# file_path2='/content/DistanceLearning_Capstone/NCES IPEDS Data 2019-2022/ef2018a_rv_2.csv'
# output_file_name = 'ef2018a_rv.csv'
# combine_csv_files(file_path1,file_path2, output_file_name)

#Processing Institutional Characteristics (hd_) files by year 2019-2022

HD files contain Institutional information in IPEDs universe.
Variables of interest:
- UNITID: Unique identification number of the institution (for merging)
- INSTNM:Institution (entity) name
- IALIAS:Institution name alias
- STABBR:State abbreviation
- OBEREG: Bureau of Economic Analysis (BEA) Regions
BEA Regions are a set of Geographic Areas that are aggregations of the states.
- ICLEVEL:A classification of whether an institutionâ€™s programs are 4-year or higher (4 year), 2-but-less-than 4-year (2 year), or less than 2-year.
- CONTROL:A classification of whether an institution is operated by publicly elected or appointed officials or by privately elected or appointed officials and derives its major source of funds from private sources.
  - Public institution - An educational institution whose programs and activities are operated by publicly elected or appointed school officials and which is supported primarily by public funds.
  - Private not-for-profit institution - A private institution in which the individual(s) or agency in control receives no compensation, other than wages, rent, or other expenses for the assumption of risk. These include both independent not-for-profit schools and those affiliated with a religious organization.
  -Private for-profit institution - A private institution in which the individual(s) or agency in control receives compensation other than wages, rent, or other expenses for the assumption of risk.

- HLOFFER:Highest level of offering (generated, based on response to IC
survey)
  - 0 - Other
  - 1 - Postsecondary award, certificate or diploma of less than one academic year
  - 2 - Postsecondary award, certificate or diploma of at least one but less than two academic years
  - 3 - Associate's degree
  - 4 - Postsecondary award, certificate or diploma of at least two but less than four academic years
  - 5 - Bachelor's degree
  - 6 - Postbaccalaureate certificate
  - 7 - Master's degree
  - 8 - Post-master's certificate
  - 9 - Doctor's degree
  - b - None of the above or no answer
   --2 - Not applicable, first-professional only
  - -3 - Not Available
- DEGGRANT:A code indicating the degree-granting status of the institution.
  - Degree-granting institutions offer an associate's, bachelor's, master's, doctor's or a first-professional degree.
  - Nondegree-granting offers certificates or other formal awards
- PSEFLAG:Postsecondary institution indicator
Identifies an institution whose primary purpose is to provide postsecondary education,is open to the general public and is currently an active (operating) institution.
- LONGITUD: Based on the location of the school, the value of LONGITUD ranges from -170 to 171.
- LATITUDE:Based on the location of the school, the value of LATITUDE ranges from -14 to 71.

In [50]:
def read_hd_files_and_createdfs(path, file_pattern, columns):
    """
    Read HD CSV files matching the given file pattern in the specified directory.
    Store DataFrames for each year in a dictionary.

    Args:
    - path (str): Directory path containing the CSV files.
    - file_pattern (str): Pattern to match the desired files (e.g., 'hd*.csv').
    - columns (list): List of columns of interest to include in the DataFrame.

    Returns:
    - dict: Dictionary containing DataFrames with years as keys.
    """

    hd_files = glob.glob(os.path.join(path, file_pattern))
    hd_file_dict = {}  # Dictionary to store DataFrames with year as key

    # Iterate through each file path
    for file_path in hd_files:
        # Extract the year from the filename
        file_name = os.path.basename(file_path)
        year = file_name[2:6]

        # Read the CSV file and save it as a DataFrame
        with open(file_path, 'rb') as file:
          df= pd.read_csv(file_path, encoding = 'unicode_escape', usecols=columns )

        # Store the DataFrame in the dictionary with year as key
        hd_file_dict[year] = df

    return hd_file_dict

# Define path, file pattern, and columns for HD files
hd_path = '/content/drive/MyDrive/Capstone_Winter2024/TABULAR DATA/INSTITUTION FILES NCES IPEDS 2018-2022'
hd_file_pattern = 'hd*.csv'
hd_columns = ('UNITID', 'INSTNM', 'IALIAS', 'STABBR', 'ICLEVEL', 'CONTROL', 'OBEREG', 'DEGGRANT', 'LONGITUD', 'LATITUDE')

# Call the function to read HD files and create DataFrames
hd_dfs = read_hd_files_and_createdfs(hd_path, hd_file_pattern, hd_columns)

# Access each DataFrame by its year
for year, df in hd_dfs.items():
    print(f"YEAR: {year}")
    print(df.head())  # Display the DataFrame

YEAR: 2018
   UNITID                               INSTNM  \
0  100654             Alabama A & M University
1  100663  University of Alabama at Birmingham
2  100690                   Amridge University
3  100706  University of Alabama in Huntsville
4  100724             Alabama State University

                                              IALIAS STABBR  OBEREG  ICLEVEL  \
0                                               AAMU     AL       5        1
1                                                        AL       5        1
2  Southern Christian University |Regions University     AL       5        1
3              UAH |University of Alabama Huntsville     AL       5        1
4                                                        AL       5        1

   CONTROL  DEGGRANT   LONGITUD   LATITUDE
0        1         1 -86.568502  34.783368
1        1         1 -86.799345  33.505697
2        2         1 -86.174010  32.362609
3        1         1 -86.640449  34.724557
4        1         1 -86.295677  32.364317
YEAR: 2019
   UNITID                               INSTNM  \
0  100654             Alabama A & M University
1  100663  University of Alabama at Birmingham
2  100690                   Amridge University
3  100706  University of Alabama in Huntsville
4  100724             Alabama State University

                                              IALIAS STABBR  OBEREG  ICLEVEL  \
0                                               AAMU     AL       5        1
1                                                        AL       5        1
2  Southern Christian University  Regions University     AL       5        1
3              UAH  University of Alabama Huntsville     AL       5        1
4                                                        AL       5        1

   CONTROL  DEGGRANT   LONGITUD   LATITUDE
0        1         1 -86.568502  34.783368
1        1         1 -86.799345  33.505697
2        2         1 -86.174010  32.362609
3        1         1 -86.640449  34.724557
4        1         1 -86.295677  32.364317
YEAR: 2020
   UNITID                               INSTNM  \
0  100654             Alabama A & M University
1  100663  University of Alabama at Birmingham
2  100690                   Amridge University
3  100706  University of Alabama in Huntsville
4  100724             Alabama State University

                                              IALIAS STABBR  OBEREG  ICLEVEL  \
0                                               AAMU     AL       5        1
1                                                        AL       5        1
2  Southern Christian University  Regions University     AL       5        1
3              UAH  University of Alabama Huntsville     AL       5        1
4                                                        AL       5        1

   CONTROL  DEGGRANT   LONGITUD   LATITUDE
0        1         1 -86.568502  34.783368
1        1         1 -86.799345  33.505697
2        2         1 -86.174010  32.362609
3        1         1 -86.640449  34.724557
4        1         1 -86.295677  32.364317
YEAR: 2021
   UNITID                               INSTNM  \
0  100654             Alabama A & M University
1  100663  University of Alabama at Birmingham
2  100690                   Amridge University
3  100706  University of Alabama in Huntsville
4  100724             Alabama State University

                                              IALIAS STABBR  OBEREG  ICLEVEL  \
0                                               AAMU     AL       5        1
1                                                UAB     AL       5        1
2  Southern Christian University  Regions University     AL       5        1
3              UAH  University of Alabama Huntsville     AL       5        1
4                                                        AL       5        1

   CONTROL  DEGGRANT   LONGITUD   LATITUDE
0        1         1 -86.568502  34.783368
1        1         1 -86.799345  33.505697
2        2         1 -86.174010  32.362609
3        1         1 -86.640449  34.724557
4        1         1 -86.295677  32.364317
YEAR: 2022
   UNITID                               INSTNM  \
0  100654             Alabama A & M University
1  100663  University of Alabama at Birmingham
2  100690                   Amridge University
3  100706  University of Alabama in Huntsville
4  100724             Alabama State University

                                              IALIAS STABBR  OBEREG  ICLEVEL  \
0                                               AAMU     AL       5        1
1                                                UAB     AL       5        1
2  Southern Christian University  Regions University     AL       5        1
3              UAH  University of Alabama Huntsville     AL       5        1
4                                                        AL       5        1

   CONTROL  DEGGRANT   LONGITUD   LATITUDE
0        1         1 -86.568502  34.783368
1        1         1 -86.799345  33.505697
2        2         1 -86.174010  32.362609
3        1         1 -86.640449  34.724557
4        1         1 -86.295677  32.364317

In [51]:

hd2018=hd_dfs.get('2018') #(6857, 10)
hd2019=hd_dfs.get('2019') #(6559, 10)
hd2020=hd_dfs.get('2020') #(6440, 10)
hd2021=hd_dfs.get('2021') #(6289, 10)
hd2022=hd_dfs.get('2022') #(6256, 10)
# hd2018.shape
# hd2018.head()

In [52]:
hd2022.head()

,UNITID,INSTNM,IALIAS,STABBR,OBEREG,ICLEVEL,CONTROL,DEGGRANT,LONGITUD,LATITUDE
0,100654,Alabama A & M University,AAMU,AL,5,1,1,1,-86.568502,34.783368
1,100663,University of Alabama at Birmingham,UAB,AL,5,1,1,1,-86.799345,33.505697
2,100690,Amridge University,Southern Christian University Regions University,AL,5,1,2,1,-86.174010,32.362609
3,100706,University of Alabama in Huntsville,UAH University of Alabama Huntsville,AL,5,1,1,1,-86.640449,34.724557
4,100724,Alabama State University,,AL,5,1,1,1,-86.295677,32.364317

#Enrollment (efYEARa_dist_rv) Files <br>
- Files contains the number of students enrolled in the fall, by distance education status and level of student.  
- Institutions with traditional academic year calendar systems (semester, quarter, trimester or  4-1-4) report their enrollment as of October 15 or the official fall reporting date of the institution.
- Institutions with calendar systems that differ by program or allow continuous enrollment report students that are enrolled at any time between August 1 and October 31.
- Files have multiple records per institution.  Records are uniquely defined by the variables IPEDS ID (UNITID), and level of student (EFDELEV).   
- Each record will contain the:
  - total education students enrolled,
  - students enrolled exclusively in distance education courses,
  - students enrolled in some education distance education courses and
  - students not enrolled in any distance education courses.
-The number of students enrolled in exclusively distance education courses are also reported by the following location categories:
  - located in the same state/jurisdiction as the institution;
  - in a different state/jurisdiction than the institution;
  - in the U.S. but the state/jurisdiction is unknown;
  - and residing outside the U.S.

Variables of interest:
- UNITID:Institution
- EFDELEV:Level and degree-seeking/non degree-seeking status of student (Undergraduate,  Undergraduate-degree/certificate seeking/non-degree/
certificate seeking, Graduate)
    - 1= All Students total
    - 2 = Undergrad total
    - 3 = Degree/Certificate seeking total
    - 11 = Non degree/certificate seeking
    - 12 = Graduate total
- EFDETOT:Grand total enrolled for credit during the fall
- EFDEEXC:Students who are enrolled only in courses that are considered distance education courses.
- EFDESOM:Students who are enrolled in at least one course that is considered a distance education course, but are not enrolled exclusively in distance education courses.
- EFDENON:Students who are not enrolled in any distance education courses.
- EFDEEX1:Students who are enrolled only in courses that are considered distance education courses that are located in the same state/jurisdiction as the institution.
- EFDEEX2:Students who are enrolled only in courses that are considered distance education courses that are lin a different state/jurisdiction than the institution.
- EFDEEX3:Students who are enrolled only in courses that are considered distance education courses in the U.S. but the state/jurisdiction is unknown
- EFDEEX4:Students who are enrolled only in courses that are considered distance education courses that are residing outside the U.S.
- EFDEEX5:Students who are enrolled only in courses that are considered distance education courses and the location is unknown/not reported

In [53]:
def read_enrollmentfiles_and_createdfs(path, file_pattern,):
    """
    Read CSV files matching the given file pattern in the specified directory.
    Store DataFrames for each year in a dictionary.

    Args:
    - path (str): Directory path containing the CSV files.
    - file_pattern (str): Pattern to match the desired files (e.g., 'ef*dist*.csv').
    - columns (list): List of columns of interest to include in the DataFrame.

    Returns:
    - dict: Dictionary containing DataFrames with years as keys.
    """

    file_paths = glob.glob(os.path.join(path, file_pattern))
    file_dict = {}  # Dictionary to store DataFrames with year as key

    # Iterate through each file path
    for file_path in file_paths:
        # Extract the year from the filename
        file_name = os.path.basename(file_path)
        year = file_name[2:6]

        # Read the CSV file and save it as a DataFrame
        with open(file_path, 'rb') as file:
          # df = pd.read_csv(file, encoding='unicode_escape', usecols=ef_columns)
          df = pd.read_csv(file, encoding='unicode_escape')

            # try:
            #     # Try reading with 'utf-8' encoding
            #     df = pd.read_csv(file, encoding='utf-8', )
            # except UnicodeDecodeError:
            #     # If UTF-8 decoding fails, try 'latin-1' encoding
                # df = pd.read_csv(file, encoding='latin-1', usecols=columns)

        #remove imputation columns
        ef_columns = ['UNITID', 'EFDELEV',  'EFDETOT', 'EFDEEXC', 'EFDESOM',  'EFDENON',  'EFDEEX1', 'EFDEEX2',  'EFDEEX3',  'EFDEEX4', 'EFDEEX5 ']
        df=df[ef_columns]

        #  # Fill 'EFDEEXC' and 'EFDESOM' with 0 where 'EFDENON' == 'EFDETOT' and 'EFDEEXC' and 'EFDESOM' are NaN
        df.loc[(df['EFDENON'] == df['EFDETOT']) & df['EFDESOM'].isna(), [ 'EFDESOM']] = 0
        df.loc[(df['EFDENON'] == df['EFDETOT']) & df['EFDEEXC'].isna(), [ 'EFDEEXC']] = 0

        # Fill 'EFDESOM' and 'EFDENON' with 0 where 'EFDEEXC' == 'EFDETOT' and 'EFDESOM' and 'EFDENON' are NaN
        df.loc[(df['EFDEEXC'] == df['EFDETOT']) & df['EFDESOM'].isna(), [ 'EFDESOM']] = 0
        df.loc[(df['EFDEEXC'] == df['EFDETOT']) & df['EFDENON'].isna(), [ 'EFDENON']] = 0




        # Store the DataFrame in the dictionary with year as key
        file_dict[year] = df

    return file_dict

# Define path, file pattern, and columns for EF files
ef_path = '/content/drive/MyDrive/Capstone_Winter2024/TABULAR DATA/DIST ENROLLMENT FILES - NCES IPEDS 2018-2022'
ef_file_pattern = 'ef*dist*.csv'
# ef_columns = ['UNITID', 'EFDELEV',  'EFDETOT',  'EFDEEXC', 'EFDESOM', 'EFDENON', 'EFDEEX1', 'EFDEEX2', 'EFDEEX3', 'EFDEEX4' 'EFDEEX5']

# Call the function to read files and create DataFrames
# ef_dfs = read_enrollmentfiles_and_createdfs(ef_path, ef_file_pattern, ef_columns)
ef_dfs = read_enrollmentfiles_and_createdfs(ef_path, ef_file_pattern)

# Access each DataFrame by its year
for year, df in ef_dfs.items():
    print(f"YEAR: {year}")
    print(df.head())  # Display the DataFrame

YEAR: 2018
   UNITID  EFDELEV  EFDETOT  EFDEEXC  EFDESOM  EFDENON  EFDEEX1  EFDEEX2  \
0  100654        1     6106    120.0   1089.0   4897.0     87.0     16.0
1  100654        2     5143     76.0    899.0   4168.0     56.0     14.0
2  100654        3     4990     75.0    894.0   4021.0     55.0     14.0
3  100654       11      153      1.0      5.0    147.0      1.0      0.0
4  100654       12      963     44.0    190.0    729.0     31.0      2.0

   EFDEEX3  EFDEEX4  EFDEEX5
0     17.0      0.0       0.0
1      6.0      0.0       0.0
2      6.0      0.0       0.0
3      0.0      0.0       0.0
4     11.0      0.0       0.0
YEAR: 2019
   UNITID  EFDELEV  EFDETOT  EFDEEXC  EFDESOM  EFDENON  EFDEEX1  EFDEEX2  \
0  100654        1     6172    102.0   1213.0   4857.0     73.0     21.0
1  100654        2     5273     83.0    986.0   4204.0     57.0     20.0
2  100654        3     5271     83.0    985.0   4203.0     57.0     20.0
3  100654       11        2      0.0      1.0      1.0      NaN      NaN
4  100654       12      899     19.0    227.0    653.0     16.0      1.0

   EFDEEX3  EFDEEX4  EFDEEX5
0      7.0      0.0       1.0
1      6.0      0.0       0.0
2      6.0      0.0       0.0
3      NaN      NaN       NaN
4      1.0      0.0       1.0
YEAR: 2020
   UNITID  EFDELEV  EFDETOT  EFDEEXC  EFDESOM  EFDENON  EFDEEX1  EFDEEX2  \
0  100654        1     5977   1869.0   3890.0    218.0   1263.0    606.0
1  100654        2     5093   1286.0   3662.0    145.0    792.0    494.0
2  100654        3     5090   1284.0   3662.0    144.0    791.0    493.0
3  100654       11        3      2.0      0.0      1.0      1.0      1.0
4  100654       12      884    583.0    228.0     73.0    471.0    112.0

   EFDEEX3  EFDEEX4  EFDEEX5
0      0.0      0.0       0.0
1      0.0      0.0       0.0
2      0.0      0.0       0.0
3      0.0      0.0       0.0
4      0.0      0.0       0.0
YEAR: 2022
   UNITID  EFDELEV  EFDETOT  EFDEEXC  EFDESOM  EFDENON  EFDEEX1  EFDEEX2  \
0  100654        1     6007    429.0   3269.0   2309.0    284.0     57.0
1  100654        2     5206    249.0   2987.0   1970.0    162.0     57.0
2  100654        3     5196    246.0   2985.0   1965.0    161.0     57.0
3  100654       11       10      3.0      2.0      5.0      1.0      0.0
4  100654       12      801    180.0    282.0    339.0    122.0      0.0

   EFDEEX3  EFDEEX4  EFDEEX5
0     37.0      0.0      51.0
1     14.0      0.0      16.0
2     12.0      0.0      16.0
3      2.0      0.0       0.0
4     23.0      0.0      35.0
YEAR: 2021
   UNITID  EFDELEV  EFDETOT  EFDEEXC  EFDESOM  EFDENON  EFDEEX1  EFDEEX2  \
0  100654        1     5969    426.0   2513.0   3030.0    276.0    125.0
1  100654        2     5107    225.0   2264.0   2618.0    147.0     71.0
2  100654        3     5098    224.0   2263.0   2611.0    146.0     71.0
3  100654       11        9      1.0      1.0      7.0      1.0      0.0
4  100654       12      862    201.0    249.0    412.0    129.0     54.0

   EFDEEX3  EFDEEX4  EFDEEX5
0     25.0      0.0       0.0
1      7.0      0.0       0.0
2      7.0      0.0       0.0
3      0.0      0.0       0.0
4     18.0      0.0       0.0

In [54]:
#retrieving individual datasets from dict
ef2018=ef_dfs.get('2018') #(21567, 20)
ef2019=ef_dfs.get('2019') #(22862, 20)
ef2020=ef_dfs.get('2020') #(22663, 20)
ef2021=ef_dfs.get('2021') #(22469, 20)
ef2022=ef_dfs.get('2022') #(22239, 20)

NOTE: For enrollment files, NAN will appear in some columns where imputation code was "A" - not applicable. These columns were included as they may provide useful insights.

In [55]:
# Nan example for institution 101471 - NANS for EFDEEX!-5 where imputation code in IPEDS dataset = "A"(Not applicable)
# ef2018[ef2018['UNITID']==102377]

In [56]:
#checking for null UNITID thorugh EDENON; NANS may appear for EFDEEX1-5 which count students only enrolled exclusively in distance education.

In [57]:
ef2018

,UNITID,EFDELEV,EFDETOT,EFDEEXC,EFDESOM,EFDENON,EFDEEX1,EFDEEX2,EFDEEX3,EFDEEX4,EFDEEX5
0,100654,1,6106,120.0,1089.0,4897.0,87.0,16.0,17.0,0.0,0.0
1,100654,2,5143,76.0,899.0,4168.0,56.0,14.0,6.0,0.0,0.0
2,100654,3,4990,75.0,894.0,4021.0,55.0,14.0,6.0,0.0,0.0
3,100654,11,153,1.0,5.0,147.0,1.0,0.0,0.0,0.0,0.0
4,100654,12,963,44.0,190.0,729.0,31.0,2.0,11.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
21562,493424,2,65,0.0,0.0,65.0,NaN,NaN,NaN,NaN,NaN
21563,493424,3,65,0.0,0.0,65.0,NaN,NaN,NaN,NaN,NaN
21564,493451,1,66,0.0,0.0,66.0,NaN,NaN,NaN,NaN,NaN
21565,493451,2,66,0.0,0.0,66.0,NaN,NaN,NaN,NaN,NaN
21566,493451,3,66,0.0,0.0,66.0,NaN,NaN,NaN,NaN,NaN

# Merging institution data  with enrollment datasets

In [58]:
def merge_hd_ef(hd_df, ef_df, year):
    """
    Merge HD and EF DataFrames for a specific year.

    Args:
    - hd_df (DataFrame): DataFrame containing HD data for a specific year.
    - ef_df (DataFrame): DataFrame containing EF data for a specific year.
    - year (str): Year for which the merge is performed.

    Returns:
    - DataFrame: Merged DataFrame for the specified year.
    """
    # Perform inner merge on 'UNITID' column
    merged_df = pd.merge(hd_df, ef_df, on='UNITID', how='inner')

    merged_df.insert(2,'YEAR',year, True)
    return merged_df


ef_dist_2018 = merge_hd_ef(hd2018, ef2018, '2018')
ef_dist_2019 = merge_hd_ef(hd2019, ef2019, '2019')
ef_dist_2020 = merge_hd_ef(hd2020, ef2020, '2020')
ef_dist_2021 = merge_hd_ef(hd2021, ef2021, '2021')
ef_dist_2022 = merge_hd_ef(hd2022, ef2022, '2022')

In [96]:
ef_dist_2018.columns

Index(['UNITID', 'INSTNM', 'YEAR', 'IALIAS', 'STABBR', 'OBEREG', 'ICLEVEL',
       'CONTROL', 'DEGGRANT', 'LONGITUD', 'LATITUDE', 'EFDELEV', 'EFDETOT',
       'EFDEEXC', 'EFDESOM', 'EFDENON', 'EFDEEX1', 'EFDEEX2', 'EFDEEX3',
       'EFDEEX4', 'EFDEEX5 '],
      dtype='object')

In [60]:
# ef_dist_2022.isnull().sum()

In [61]:
combined_enrollment=pd.concat([ef_dist_2018.reset_index(drop=True),
                               ef_dist_2019.reset_index(drop=True),
                                   ef_dist_2020.reset_index(drop=True),
                                   ef_dist_2021.reset_index(drop=True),
                                   ef_dist_2022.reset_index(drop=True)])

In [62]:
# combined_enrollment.shape #111800 rows Ã— 22 columns

In [63]:
# combined_enrollment.to_csv('dist_enrollment18_22.csv', index=False)

In [64]:
# combined_enrollment.isnull().sum()

#Race, Gender, Level  with institution identifying names

Variables of Interest:
  - EFALEVEL: 13 codes for full-time/part-time by undergrad, grad, degree-seeking, non-degree seeking
  -RACE/ETHNICITY- see codes, separated by EFXXXT (Total), EFXXXM=Men, EFXXXXW=Women

In [65]:
def read_demogfiles_and_createdfs(path, file_pattern, columns):
    """
    Read "f YEARa"(race/eth, gender, attend/level) and "efYEARb"(age/gender/attend/level) CSV files matching the given file pattern in the specified directory.
    Store DataFrames for each year in a dictionary.

    Args:
    - path (str): Directory path containing the CSV files.
    - file_pattern (str): Pattern to match the desired files (e.g., *.csv').
    - columns (list): List of columns of interest to include in the DataFrame.

    Returns:
    - dict: Dictionary containing DataFrames with years as keys.
    """

    demog_files = glob.glob(os.path.join(path, file_pattern))
    demog_file_dict = {}  # Dictionary to store DataFrames with year as key

    for file_path in demog_files:
        file_name = os.path.basename(file_path)  # Get the filename from the path
        year = file_name[2:6]  # Extract the year from the filename
        demog_file_dict[year] = file_path  # Store the file path in the dictionary with year as ke

        # Read the CSV file and save it as a DataFrame
        with open(file_path, 'rb') as file:
          # df= pd.read_csv(file_path, encoding = 'unicode_escape', usecols=columns )

          df= pd.read_csv(file_path, encoding = 'unicode_escape' )

          # Strip whitespace at end of all columns
          df = df.rename(columns={col: col.rstrip() for col in df.columns})

          df= df[columns]


        # Store the DataFrame in the dictionary with year as key
        demog_file_dict[year] = df

    return demog_file_dict

In [66]:
# Define path, file pattern, and columns for demographic files
racial_path = '/content/drive/MyDrive/Capstone_Winter2024/TABULAR DATA/RACE_GENDER_ATTEND_LEVEL NCES IPEDS 2018-2022'
racial_file_pattern = '*.csv'
racial_columns = ['UNITID','EFALEVEL','EFALEVEL', 'LINE', 'SECTION', 'LSTUDY',
                       'EFTOTLT', 'EFTOTLM', 'EFTOTLW',
                      'EFAIANT', 'EFAIANM', 'EFAIANW', 'EFASIAT',
                      'EFASIAM', 'EFASIAW', 'EFBKAAT', 'EFBKAAM',
                      'EFBKAAW', 'EFHISPT', 'EFHISPM', 'EFHISPW',
                      'EFNHPIT', 'EFNHPIM', 'EFNHPIW', 'EFWHITT',
                      'EFWHITM', 'EFWHITW', 'EF2MORT', 'EF2MORM',
                      'EF2MORW', 'EFUNKNT', 'EFUNKNM', 'EFUNKNW',
                      'EFNRALT', 'EFNRALM','EFNRALW']


racial_dfs = read_demogfiles_and_createdfs(racial_path, racial_file_pattern, racial_columns)
# racial_dfs = read_demogfiles_and_createdfs(racial_path, racial_file_pattern)

# Access each DataFrame by its year
for year, df in racial_dfs.items():
    print(f"YEAR: {year}")
    print(df.head())  # Display the DataFrame

YEAR: 2018
   UNITID  EFALEVEL  EFALEVEL  LINE  SECTION  LSTUDY  EFTOTLT  EFTOTLM  \
0  100654         1         1    29        3       4     6106     2381
1  100654         2         2    99        3       1     5143     2106
2  100654         3         3    99        3       1     4990     2034
3  100654         4         4    99        3       1     1405      572
4  100654         5         5    99        3       1     3585     1462

   EFTOTLW  EFAIANT  ...  EFWHITW  EF2MORT  EF2MORM  EF2MORW  EFUNKNT  \
0     3725       15  ...       96       65       20       45      301
1     3037       12  ...       41       60       18       42      191
2     2956       11  ...       38       59       18       41      180
3      833        3  ...        5       18        2       16       50
4     2123        8  ...       33       41       16       25      130

   EFUNKNM  EFUNKNW  EFNRALT  EFNRALM  EFNRALW
0       97      204       70       34       36
1       75      116       37       20       17
2       69      111       35       20       15
3       25       25        3        1        2
4       44       86       32       19       13

[5 rows x 36 columns]
YEAR: 2019
   UNITID  EFALEVEL  EFALEVEL  LINE  SECTION  LSTUDY  EFTOTLT  EFTOTLM  \
0  100654         1         1    29        3       4     6172     2364
1  100654         2         2    99        3       1     5273     2091
2  100654         3         3    99        3       1     5271     2091
3  100654         4         4    99        3       1     1694      647
4  100654         5         5    99        3       1     3577     1444

   EFTOTLW  EFAIANT  ...  EFWHITW  EF2MORT  EF2MORM  EF2MORW  EFUNKNT  \
0     3808       15  ...       64       65       23       42      407
1     3182       11  ...       29       60       21       39      243
2     3180       11  ...       28       60       21       39      243
3     1047        2  ...        8       23        8       15       76
4     2133        9  ...       20       37       13       24      167

   EFUNKNM  EFUNKNW  EFNRALT  EFNRALM  EFNRALW
0      129      278       79       40       39
1       86      157       37       20       17
2       86      157       37       20       17
3       26       50       11        5        6
4       60      107       26       15       11

[5 rows x 36 columns]
YEAR: 2020
   UNITID  EFALEVEL  EFALEVEL  LINE  SECTION  LSTUDY  EFTOTLT  EFTOTLM  \
0  100654         1         1    29        3       4     5977     2302
1  100654         2         2    99        3       1     5093     2026
2  100654         3         3    99        3       1     5090     2025
3  100654         4         4    99        3       1     1535      636
4  100654         5         5    99        3       1     3555     1389

   EFTOTLW  EFAIANT  ...  EFWHITW  EF2MORT  EF2MORM  EF2MORW  EFUNKNT  \
0     3675       17  ...       54       76       25       51      478
1     3067       14  ...       33       73       24       49      224
2     3065       14  ...       33       73       24       49      224
3      899        5  ...        6       31       11       20       55
4     2166        9  ...       27       42       13       29      169

   EFUNKNM  EFUNKNW  EFNRALT  EFNRALM  EFNRALW
0      160      318       76       37       39
1       85      139       37       18       19
2       85      139       37       18       19
3       30       25        3        3        0
4       55      114       34       15       19

[5 rows x 36 columns]
YEAR: 2021
   UNITID  EFALEVEL  EFALEVEL  LINE  SECTION  LSTUDY  EFTOTLT  EFTOTLM  \
0  100654         1         1    29        3       4     5969     2353
1  100654         2         2    99        3       1     5107     2072
2  100654         3         3    99        3       1     5098     2070
3  100654         4         4    99        3       1     1477      619
4  100654         5         5    99        3       1     3621     1451

   EFTOTLW  EFAIANT  ...  EFWHITW  EF2MORT  EF2MORM  EF2MORW  EFUNKNT  \
0     3616       16  ...       57       57       20       37      525
1     3035       14  ...       43       55       20       35      246
2     3028       14  ...       42       55       20       35      244
3      858        3  ...        5       19        6       13       98
4     2170       11  ...       37       36       14       22      146

   EFUNKNM  EFUNKNW  EFNRALT  EFNRALM  EFNRALW
0      174      351       81       40       41
1       87      159       44       22       22
2       87      157       44       22       22
3       34       64        6        3        3
4       53       93       38       19       19

[5 rows x 36 columns]
YEAR: 2022
   UNITID  EFALEVEL  EFALEVEL  LINE  SECTION  LSTUDY  EFTOTLT  EFTOTLM  \
0  100654         1         1    29        3       4     6007     2369
1  100654         2         2    99        3       1     5206     2111
2  100654         3         3    99        3       1     5196     2107
3  100654         4         4    99        3       1     1557      622
4  100654         5         5    99        3       1     3639     1485

   EFTOTLW  EFAIANT  ...  EFWHITW  EF2MORT  EF2MORM  EF2MORW  EFUNKNT  \
0     3638       16  ...       66       66       20       46      473
1     3095       13  ...       57       66       20       46      228
2     3089       13  ...       57       66       20       46      226
3      935        3  ...       11       23        6       17       77
4     2154       10  ...       46       43       14       29      149

   EFUNKNM  EFUNKNW  EFNRALT  EFNRALM  EFNRALW
0      180      293      110       66       44
1      105      123       60       38       22
2      104      122       60       38       22
3       42       35       19       17        2
4       62       87       41       21       20

[5 rows x 36 columns]

In [67]:
#retrieving individual datasets from dict
rg2018=racial_dfs.get('2018') #(121842, 36)
rg2019=racial_dfs.get('2019') #(118917, 36)
rg2020=racial_dfs.get('2020') #(117881, 36)
rg2021=racial_dfs.get('2021') #(116965, 36)
rg2022=racial_dfs.get('2022') #(116110, 36)
rg2022.shape

(116110, 36)

In [68]:
rg2022.shape
# rg2021.columns
# #2022 columns not in other datasets- remove
# cols_drop=['XEFGNDRU', 'EFGNDRUN', 'XEFGNDRA', 'EFGNDRAN',
# 'XEFGNDRU.1', 'EFGNDRUA', 'XEFGNDRK', 'EFGNDRKN']
# rg2022=rg2022.drop(columns=cols_drop, axis=1)
# # rg2022 = rg2022.rename(columns={'LEVEL': 'EFALEVEL'})
# rg2022.shape

(116110, 36)

##Merge race/gender data with institution (hd files). <br>
NOTE: Cannot merge IPEDS demographic files (race, age) with dist_enrollment files as race/gender is for ALL institution students and does not identify distance education demographics specifically

In [69]:
#merge race/gender data with institution information (hd)

def demog_merge(df1, df2, year):
  merged_df=pd.merge(df1, df2,  on='UNITID',how='inner')

      # Add year as a column
  # merged_df['YEAR'] = year
  merged_df.insert(2,'YEAR',year, True)
  return merged_df


insts_racial_2018=demog_merge(hd2018, rg2018, '2018')
insts_racial_2019=demog_merge(hd2019, rg2019,'2019')
insts_racial_2020=demog_merge(hd2020, rg2020,'2020')
insts_racial_2021=demog_merge(hd2021, rg2021,'2021')
insts_racial_2022=demog_merge(hd2022, rg2022,'2022')

In [70]:
insts_racial_2018.columns

Index(['UNITID', 'INSTNM', 'YEAR', 'IALIAS', 'STABBR', 'OBEREG', 'ICLEVEL',
       'CONTROL', 'DEGGRANT', 'LONGITUD', 'LATITUDE', 'EFALEVEL', 'EFALEVEL',
       'LINE', 'SECTION', 'LSTUDY', 'EFTOTLT', 'EFTOTLM', 'EFTOTLW', 'EFAIANT',
       'EFAIANM', 'EFAIANW', 'EFASIAT', 'EFASIAM', 'EFASIAW', 'EFBKAAT',
       'EFBKAAM', 'EFBKAAW', 'EFHISPT', 'EFHISPM', 'EFHISPW', 'EFNHPIT',
       'EFNHPIM', 'EFNHPIW', 'EFWHITT', 'EFWHITM', 'EFWHITW', 'EF2MORT',
       'EF2MORM', 'EF2MORW', 'EFUNKNT', 'EFUNKNM', 'EFUNKNW', 'EFNRALT',
       'EFNRALM', 'EFNRALW'],
      dtype='object')

In [71]:

combined_racegender= pd.concat([insts_racial_2018.reset_index(drop=True),
                              insts_racial_2019.reset_index(drop=True),
                                   insts_racial_2020.reset_index(drop=True),
                                  insts_racial_2021.reset_index(drop=True),
                                   insts_racial_2022.reset_index(drop=True)])

In [72]:
# combined_racegender.isnull().sum()

In [73]:
combined_racegender.to_csv('race_gen_by_inst_18_22.csv', index=False)

#AGE, GENDER, LEVEL with identifying institution names
Variables of interest:
  - EFBAGE: Age Categories - See Code dict
  - LStudy: Level of student
  - EFAFE 01-09 Full-time Men/Women, Part-Time Men/Women

In [74]:
# Define path, file pattern, and columns for demographic files
age_path = '/content/drive/MyDrive/Capstone_Winter2024/TABULAR DATA/AGE_GENDER_LEVEL NCES IPEDs 2018-2022'
age_file_pattern = '*.csv'
age_columns = ['UNITID', 'EFBAGE', 'LINE', 'LSTUDY', 'EFAGE01',
       'EFAGE02', 'EFAGE03',  'EFAGE04',  'EFAGE05',  'EFAGE06', 'EFAGE07',
       'EFAGE08', 'EFAGE09']


age_dfs = read_demogfiles_and_createdfs(age_path, age_file_pattern, age_columns)
# racial_dfs = read_demogfiles_and_createdfs(racial_path, racial_file_pattern)

# Access each DataFrame by its year
for year, df in age_dfs.items():
    print(f"YEAR: {year}")
    print(df.head())  # Display the DataFrame

YEAR: 2018
   UNITID  EFBAGE  LINE  LSTUDY  EFAGE01  EFAGE02  EFAGE03  EFAGE04  EFAGE05  \
0  100654       1   412       1     2140     3352      241      373     5492
1  100654       1   112       2     1967     2875      139      162     4842
2  100654       1   312       5      173      477      102      211      650
3  100654       2   999       1     1924     2974      116      132     4898
4  100654       2   999       2     1869     2741      103       99     4610

   EFAGE06  EFAGE07  EFAGE08  EFAGE09
0      614     2381     3725     6106
1      301     2106     3037     5143
2      313      275      688      963
3      248     2040     3106     5146
4      202     1972     2840     4812
YEAR: 2019
   UNITID  EFBAGE  LINE  LSTUDY  EFAGE01  EFAGE02  EFAGE03  EFAGE04  EFAGE05  \
0  100654       1   412       1     2118     3454      246      354     5572
1  100654       1   112       2     1951     3024      140      158     4975
2  100654       1   312       5      167      430      106      196      597
3  100654       2   999       1     1980     3187      135      174     5167
4  100654       2   999       2     1896     2949      111      115     4845

   EFAGE06  EFAGE07  EFAGE08  EFAGE09
0      600     2364     3808     6172
1      298     2091     3182     5273
2      302      273      626      899
3      309     2115     3361     5476
4      226     2007     3064     5071
YEAR: 2020
   UNITID  EFBAGE  LINE  LSTUDY  EFAGE01  EFAGE02  EFAGE03  EFAGE04  EFAGE05  \
0  100654       1   412       1     2023     3226      279      449     5249
1  100654       1   112       2     1849     2814      177      253     4663
2  100654       1   312       5      174      412      102      196      586
3  100654       2   999       1     1827     2870      152      248     4697
4  100654       2   999       2     1766     2710      138      200     4476

   EFAGE06  EFAGE07  EFAGE08  EFAGE09
0      728     2302     3675     5977
1      430     2026     3067     5093
2      298      276      608      884
3      400     1979     3118     5097
4      338     1904     2910     4814
YEAR: 2021
   UNITID  EFBAGE  LINE  LSTUDY  EFAGE01  EFAGE02  EFAGE03  EFAGE04  EFAGE05  \
0  100654       1   412       1     1986     3078      367      538     5064
1  100654       1   112       2     1823     2706      249      329     4529
2  100654       1   312       5      163      372      118      209      535
3  100654       2   999       1     1818     2766      230      292     4584
4  100654       2   999       2     1743     2596      202      251     4339

   EFAGE06  EFAGE07  EFAGE08  EFAGE09
0      905     2353     3616     5969
1      578     2072     3035     5107
2      327      281      581      862
3      522     2048     3058     5106
4      453     1945     2847     4792
YEAR: 2022
   UNITID  EFBAGE  LINE  LSTUDY  EFAGE01  EFAGE02  EFAGE03  EFAGE04  EFAGE05  \
0  100663       1   412       1     5686     9394     2217     4342    15080
1  100663       1   112       2     3836     6427     1048     1721    10263
2  100663       1   312       5     1850     2967     1169     2621     4817
3  100663       2   999       1     4333     7400      662     1185    11733
4  100663       2   999       2     3561     6088      504      785     9649

   EFAGE06  EFAGE07  EFAGE08  EFAGE09
0     6559     7903    13736    21639
1     2769     4884     8148    13032
2     3790     3019     5588     8607
3     1847     4995     8585    13580
4     1289     4065     6873    10938

In [75]:
#retrieving individual datasets from dict
age2018=age_dfs.get('2018') #(81449, 13)
age2019=age_dfs.get('2019') #(164753, 13)
age2020=age_dfs.get('2020') #(78024, 13)
age2021=age_dfs.get('2021') #(161174, 13)
age2022=age_dfs.get('2022') #(77996, 13)
age2018.shape

(81449, 13)

In [76]:
#merge age with hd -institutional information
age_2018=demog_merge(hd2018, age2018, '2018')
age_2019=demog_merge(hd2019, age2019, '2019')
age_2020=demog_merge(hd2020, age2020, '2020')
age_2021=demog_merge(hd2021, age2021, '2021')
age_2022=demog_merge(hd2022, age2022, '2022')

In [77]:
# age_2018.head()

In [78]:
combined_age_gen_lev= pd.concat([age_2018.reset_index(drop=True),
                                age_2019.reset_index(drop=True),
                                   age_2020.reset_index(drop=True),
                                   age_2021.reset_index(drop=True),
                                   age_2022.reset_index(drop=True)])

In [79]:
# combined_age_gen_lev.isnull().sum()

In [80]:
combined_age_gen_lev.to_csv('age_gen_by_inst_18_22.csv', index=False)

#Completion (c_) Files

-File contains the number of programs offered, by:
  - type of program, level of award (certificate or degree) and distance education status.
- Type of program is categorized according to the Classification of Instructional Programs (CIP), a detailed coding system for postsecondary instructional programs.
- File contains multiple records per institution.
- Each record will contain the total number of programs offered and the total number of programs offered via distance education.
- Six digit CIPCODE (XX.NNNN) records will identify which award levels are offered and which award levels are offered via distance learning (1=Yes, 0=No). - Two digit CIPCODE (XX) summary records will contain the number of 6-digit CIPCODES under the  2-digit group that are offered by award level and distance education status and CIPCODE (99)  will contain totals for the institution. Program offerings were derived from completions data that were granted between July 1,Fall_YEAR and June 30, Spring_YEAR.

Variables of interest:
(Note 2020 and on C file have additional variables distinguishing between coursed in CIP codes can all be accessed vs. some making 41 total variables . The some variables being removed for consistency with 2019 dataset(26 total variables))
  1. UNITID:Unique identification number of the institution
  2.CIPCODE: A six-digit code in the form xx.xxxx that identifies instructional  program specialties within educational institutions.
  3. PTOTAL: Number of programs offered is the sum of all programs offered at all award levels.  See details of each award level category
  4.PTOTALDE: Number of programs offered via distance education is the sum of all programs offered via distance education.  See details of each award level category
  5.PASSOC:Number of Associate's degree programs offered
  6.PASSOCDE:Number of Associate's degree programs offered via distance education
  7.PBACHL:Number of Bachelor's degree programs offered
  8.PBACHLDE:Number of Bachelor's degree programs offered via distance education/Bachelor's degree - all programs in a CIP code can be completed entirely via distance education
  9. PMASTR:Number of Master's degree programs offered
  10. PMASTRDE:Number of Master's degree programs offered via distance education/Master's degree - all programs in a CIP code can be completed entirely via distance education
  11. PDOCRS:Number of Doctor's degree-research/scholarship programs offered
  12. PDOCRSDE:Number of Doctor's degree-research/scholarship programs offered via distance education
  13. PDOCPP:Number of Doctor's degree-professional practice programs offered
  14. PDOCPPDE:Number of Doctor's degree-professional practice programs offered via distance education
  15. PDOCOT: Number of Doctor's degree-other programs offered
  16.PDOCOTDE: Number of Doctor's degree-other programs offered via distance education offered via distance education
  17.PCERT1:Number of less than 1-year certificate programs offered
  18. PCERT1DE: Number of less than 1-year certificate programs offered via distance education
  19. PCERT2:Number of 1-year, but less than-2-year certificate programs offered
  20. PCERT2DE:Number of 1-year, but less than 2-year certificate programs offered via distance education
  21. PCERT4: Number of 2-year, but less than 4-year certificate programs offered
  22. PCERT4DE: Number of 2-year, but less than 4-year certificate programs offered via distance education
  23. PPBACC:Number of Postbaccalaureate certificate programs offered
  24. PPBACCDE:Number of Postbaccalaureate certificate programs offered via distance education
  25. PPMAST:Number of Post-master's certificate programs offered
  26. PPMASTDE:Number of Post-master's certificate programs offered via distance education

In [81]:
def readcompletes_and_getdfs(directory_path):
    """
    Retrieves DE completes datasets by years from the given directory path.

    Args:
    directory_path (str): The directory path containing the DE completes datasets.

    Returns:
    dict: A dictionary containing file paths with year as key.
    """
    c_files = glob.glob(os.path.join(directory_path, 'c*.csv'))
    c_file_dict = {}

    for file_path in c_files:
        file_name = os.path.basename(file_path)
        year = file_name[1:5]

        df = pd.read_csv(file_path)  # Read CSV file into DataFrame

        df.columns = df.columns.str.strip()
        c_file_dict[year] = df

    return c_file_dict

# Example usage:
directory_path = '/content/drive/MyDrive/Capstone_Winter2024/TABULAR DATA/COMPLETIONS FILES- NCES IPEDS 2018-2022'
c_file_dict = readcompletes_and_getdfs(directory_path)

# Access each file by its year
for year, file_path in c_file_dict.items():
    print(f"Year: {year}, File Path: {file_path}")

Year: 2018, File Path:         UNITID  CIPCODE  PTOTAL  PTOTALDE  PASSOC  PASSOCDE  PBACHL  PBACHLDE  \
0       100654   1.0000       7         0       0         0       3         0
1       100654   1.0999       1         0       0         0       1         0
2       100654   1.1001       3         0       0         0       1         0
3       100654   1.9999       3         0       0         0       1         0
4       100654   3.0000       1         0       0         0       1         0
...        ...      ...     ...       ...     ...       ...     ...       ...
240789  493424  99.0000       3         0       0         0       0         0
240790  493451  51.0000       3         0       1         0       0         0
240791  493451  51.0801       2         0       1         0       0         0
240792  493451  51.3501       1         0       0         0       0         0
240793  493451  99.0000       3         0       1         0       0         0

        PMASTR  PMASTRDE  ...  PCERT1  PCERT1DE  PCERT2  PCERT2DE  PCERT4  \
0            2         0  ...       0         0       0         0       0
1            0         0  ...       0         0       0         0       0
2            1         0  ...       0         0       0         0       0
3            1         0  ...       0         0       0         0       0
4            0         0  ...       0         0       0         0       0
...        ...       ...  ...     ...       ...     ...       ...     ...
240789       0         0  ...       2         0       1         0       0
240790       0         0  ...       0         0       2         0       0
240791       0         0  ...       0         0       1         0       0
240792       0         0  ...       0         0       1         0       0
240793       0         0  ...       0         0       2         0       0

        PCERT4DE  PPBACC  PPBACCDE  PPMAST  PPMASTDE
0              0       0         0       0         0
1              0       0         0       0         0
2              0       0         0       0         0
3              0       0         0       0         0
4              0       0         0       0         0
...          ...     ...       ...     ...       ...
240789         0       0         0       0         0
240790         0       0         0       0         0
240791         0       0         0       0         0
240792         0       0         0       0         0
240793         0       0         0       0         0

[240794 rows x 26 columns]
Year: 2019, File Path:         UNITID  CIPCODE  PTOTAL  PTOTALDE  PASSOC  PASSOCDE  PBACHL  PBACHLDE  \
0       100654   1.0000       7         0       0         0       3         0
1       100654   1.0999       1         0       0         0       1         0
2       100654   1.1001       3         0       0         0       1         0
3       100654   1.9999       3         0       0         0       1         0
4       100654   3.0000       1         0       0         0       1         0
...        ...      ...     ...       ...     ...       ...     ...       ...
240407  494904  51.0805       1         0       0         0       0         0
240408  494904  51.0899       1         0       0         0       0         0
240409  494904  51.3902       1         0       0         0       0         0
240410  494904  51.3999       1         0       0         0       0         0
240411  494904  99.0000       4         0       0         0       0         0

        PMASTR  PMASTRDE  ...  PCERT1  PCERT1DE  PCERT2  PCERT2DE  PCERT4  \
0            2         0  ...       0         0       0         0       0
1            0         0  ...       0         0       0         0       0
2            1         0  ...       0         0       0         0       0
3            1         0  ...       0         0       0         0       0
4            0         0  ...       0         0       0         0       0
...        ...       ...  ...     ...       ...     ...       ...     ...
240407       0         0  ...       1         0       0         0       0
240408       0         0  ...       1         0       0         0       0
240409       0         0  ...       1         0       0         0       0
240410       0         0  ...       1         0       0         0       0
240411       0         0  ...       4         0       0         0       0

        PCERT4DE  PPBACC  PPBACCDE  PPMAST  PPMASTDE
0              0       0         0       0         0
1              0       0         0       0         0
2              0       0         0       0         0
3              0       0         0       0         0
4              0       0         0       0         0
...          ...     ...       ...     ...       ...
240407         0       0         0       0         0
240408         0       0         0       0         0
240409         0       0         0       0         0
240410         0       0         0       0         0
240411         0       0         0       0         0

[240412 rows x 26 columns]
Year: 2020, File Path:         UNITID  CIPCODE  PTOTAL  PTOTALDE  PTOTALDES  PASSOC  PASSOCDE  \
0       100654   1.0000       7         0          0       0         0
1       100654   1.0999       1         0          0       0         0
2       100654   1.1001       3         0          0       0         0
3       100654   1.9999       3         0          0       0         0
4       100654   3.0000       1         0          0       0         0
...        ...      ...     ...       ...        ...     ...       ...
238684  496423  12.0413       1         0          0       0         0
238685  496423  12.0414       1         0          0       0         0
238686  496423  51.0000       1         0          0       0         0
238687  496423  51.3501       1         0          0       0         0
238688  496423  99.0000       7         0          0       0         0

        PASSOCDES  PBACHL  PBACHLDE  ...  PCERT2DES  PCERT4  PCERT4DE  \
0               0       3         0  ...          0       0         0
1               0       1         0  ...          0       0         0
2               0       1         0  ...          0       0         0
3               0       1         0  ...          0       0         0
4               0       1         0  ...          0       0         0
...           ...     ...       ...  ...        ...     ...       ...
238684          0       0         0  ...          0       0         0
238685          0       0         0  ...          0       0         0
238686          0       0         0  ...          0       0         0
238687          0       0         0  ...          0       0         0
238688          0       0         0  ...          0       0         0

        PCERT4DES  PPBACC  PPBACCDE  PPBACCDES  PPMAST  PPMASTDE  PPMASTDES
0               0       0         0          0       0         0          0
1               0       0         0          0       0         0          0
2               0       0         0          0       0         0          0
3               0       0         0          0       0         0          0
4               0       0         0          0       0         0          0
...           ...     ...       ...        ...     ...       ...        ...
238684          0       0         0          0       0         0          0
238685          0       0         0          0       0         0          0
238686          0       0         0          0       0         0          0
238687          0       0         0          0       0         0          0
238688          0       0         0          0       0         0          0

[238689 rows x 41 columns]
Year: 2021, File Path:         UNITID  CIPCODE  PTOTAL  PTOTALDE  PTOTALDES  PASSOC  PASSOCDE  \
0       100654   1.0000       7         0          0       0         0
1       100654   1.0999       1         0          0       0         0
2       100654   1.1001       3         0          0       0         0
3       100654   1.9999       3         0          0       0         0
4       100654   3.0000       1         0          0       0         0
...        ...      ...     ...       ...        ...     ...       ...
241821  497329  99.0000       3         0          0       0         0
241822  497338  51.0000       2         0          0       1         0
241823  497338  51.0801       1         0          0       0         0
241824  497338  51.3801       1         0          0       1         0
241825  497338  99.0000       2         0          0       1         0

        PASSOCDES  PBACHL  PBACHLDE  ...  PCERT2DES  PCERT4  PCERT4DE  \
0               0       3         0  ...          0       0         0
1               0       1         0  ...          0       0         0
2               0       1         0  ...          0       0         0
3               0       1         0  ...          0       0         0
4               0       1         0  ...          0       0         0
...           ...     ...       ...  ...        ...     ...       ...
241821          0       0         0  ...          0       0         0
241822          0       0         0  ...          0       0         0
241823          0       0         0  ...          0       0         0
241824          0       0         0  ...          0       0         0
241825          0       0         0  ...          0       0         0

        PCERT4DES  PPBACC  PPBACCDE  PPBACCDES  PPMAST  PPMASTDE  PPMASTDES
0               0       0         0          0       0         0          0
1               0       0         0          0       0         0          0
2               0       0         0          0       0         0          0
3               0       0         0          0       0         0          0
4               0       0         0          0       0         0          0
...           ...     ...       ...        ...     ...       ...        ...
241821          0       0         0          0       0         0          0
241822          0       0         0          0       0         0          0
241823          0       0         0          0       0         0          0
241824          0       0         0          0       0         0          0
241825          0       0         0          0       0         0          0

[241826 rows x 41 columns]
Year: 2022, File Path:         UNITID  CIPCODE  PTOTAL  PTOTALDE  PTOTALDES  PASSOC  PASSOCDE  \
0       100654   1.0000       7         0          0       0         0
1       100654   1.0999       1         0          0       0         0
2       100654   1.1001       3         0          0       0         0
3       100654   1.9999       3         0          0       0         0
4       100654   3.0000       1         0          0       0         0
...        ...      ...     ...       ...        ...     ...       ...
243999  498571  52.1401       1         0          0       0         0
244000  498571  52.1501       2         0          0       0         0
244001  498571  54.0000       2         0          0       0         0
244002  498571  54.0101       2         0          0       0         0
244003  498571  99.0000     254       102         26      28         6

        PASSOCDES  PBACHL  PBACHLDE  ...  PCERT2DES  PCERT4  PCERT4DE  \
0               0       3         0  ...          0       0         0
1               0       1         0  ...          0       0         0
2               0       1         0  ...          0       0         0
3               0       1         0  ...          0       0         0
4               0       1         0  ...          0       0         0
...           ...     ...       ...  ...        ...     ...       ...
243999          0       1         0  ...          0       0         0
244000          0       1         0  ...          0       0         0
244001          0       1         0  ...          0       0         0
244002          0       1         0  ...          0       0         0
244003          3     100        12  ...          0       0         0

        PCERT4DES  PPBACC  PPBACCDE  PPBACCDES  PPMAST  PPMASTDE  PPMASTDES
0               0       0         0          0       0         0          0
1               0       0         0          0       0         0          0
2               0       0         0          0       0         0          0
3               0       0         0          0       0         0          0
4               0       0         0          0       0         0          0
...           ...     ...       ...        ...     ...       ...        ...
243999          0       0         0          0       0         0          0
244000          0       0         0          0       0         0          0
244001          0       0         0          0       0         0          0
244002          0       0         0          0       0         0          0
244003          0      42        35          3      13         6          1

[244004 rows x 41 columns]

In [82]:
#retrieving individual datasets from dict
c2018=c_file_dict.get('2018') #(240412, 26)
c2019=c_file_dict.get('2019') #(240412, 26)
c2020=c_file_dict.get('2020') #(238689, 41) updated to 26 columns below
c2021=c_file_dict.get('2021') #(241826, 41) updated to 26 columns below
c2022=c_file_dict.get('2022') #(244004, 41) updated to 26 columns below

In [83]:
# c2022.shape

In [84]:
c2018.columns

Index(['UNITID', 'CIPCODE', 'PTOTAL', 'PTOTALDE', 'PASSOC', 'PASSOCDE',
       'PBACHL', 'PBACHLDE', 'PMASTR', 'PMASTRDE', 'PDOCRS', 'PDOCRSDE',
       'PDOCPP', 'PDOCPPDE', 'PDOCOT', 'PDOCOTDE', 'PCERT1', 'PCERT1DE',
       'PCERT2', 'PCERT2DE', 'PCERT4', 'PCERT4DE', 'PPBACC', 'PPBACCDE',
       'PPMAST', 'PPMASTDE'],
      dtype='object')

In [85]:
c2022.columns

Index(['UNITID', 'CIPCODE', 'PTOTAL', 'PTOTALDE', 'PTOTALDES', 'PASSOC',
       'PASSOCDE', 'PASSOCDES', 'PBACHL', 'PBACHLDE', 'PBACHLDES', 'PMASTR',
       'PMASTRDE', 'PMASTRDES', 'PDOCRS', 'PDOCRSDE', 'PDOCRSDES', 'PDOCPP',
       'PDOCPPDE', 'PDOCPPDES', 'PDOCOT', 'PDOCOTDE', 'PDOCOTDES', 'PCERT1A',
       'PCERT1ADE', 'PCERT1ADES', 'PCERT1B', 'PCERT1BDE', 'PCERT1BDES',
       'PCERT2', 'PCERT2DE', 'PCERT2DES', 'PCERT4', 'PCERT4DE', 'PCERT4DES',
       'PPBACC', 'PPBACCDE', 'PPBACCDES', 'PPMAST', 'PPMASTDE', 'PPMASTDES'],
      dtype='object')

In [86]:
# #Columns differ between 2018 & 2019 with more being added beginning in 2020
# #function to add missing columns and fill with N/A for dataset consistency
columns_to_check =['UNITID', 'CIPCODE', 'PTOTAL', 'PTOTALDE', 'PTOTALDES', 'PASSOC',
       'PASSOCDE', 'PASSOCDES', 'PBACHL', 'PBACHLDE', 'PBACHLDES', 'PMASTR',
       'PMASTRDE', 'PMASTRDES', 'PDOCRS', 'PDOCRSDE', 'PDOCRSDES', 'PDOCPP',
       'PDOCPPDE', 'PDOCPPDES', 'PDOCOT', 'PDOCOTDE', 'PDOCOTDES', 'PCERT1A',
       'PCERT1ADE', 'PCERT1ADES', 'PCERT1B', 'PCERT1BDE', 'PCERT1BDES',
       'PCERT2', 'PCERT2DE', 'PCERT2DES', 'PCERT4', 'PCERT4DE', 'PCERT4DES',
       'PPBACC', 'PPBACCDE', 'PPBACCDES', 'PPMAST', 'PPMASTDE', 'PPMASTDES']

def check_cols(df, cols_to_check):
    # Identify missing columns
    missing_columns = set(columns_to_check) - set(df.columns)

    # Add missing columns to df
    for column in missing_columns:
        df[column] = 'N/A'

    # Reorder columns
    df=df[columns_to_check]
    return df

In [87]:
c2018_2= check_cols(c2018, columns_to_check)
c2019_2= check_cols(c2019, columns_to_check)

# c2019= check_cols(c2019, cols_to_check)

# c2020= check_cols(c2020, cols_to_check)
# c2021= check_cols(c2021, cols_to_check)
# c2022= check_cols(c2022, cols_to_check)

In [88]:
c2019_2.head()

,UNITID,CIPCODE,PTOTAL,PTOTALDE,PTOTALDES,PASSOC,PASSOCDE,PASSOCDES,PBACHL,PBACHLDE,...,PCERT2DES,PCERT4,PCERT4DE,PCERT4DES,PPBACC,PPBACCDE,PPBACCDES,PPMAST,PPMASTDE,PPMASTDES
0,100654,1.0000,7,0,N/A,0,0,N/A,3,0,...,N/A,0,0,N/A,0,0,N/A,0,0,N/A
1,100654,1.0999,1,0,N/A,0,0,N/A,1,0,...,N/A,0,0,N/A,0,0,N/A,0,0,N/A
2,100654,1.1001,3,0,N/A,0,0,N/A,1,0,...,N/A,0,0,N/A,0,0,N/A,0,0,N/A
3,100654,1.9999,3,0,N/A,0,0,N/A,1,0,...,N/A,0,0,N/A,0,0,N/A,0,0,N/A
4,100654,3.0000,1,0,N/A,0,0,N/A,1,0,...,N/A,0,0,N/A,0,0,N/A,0,0,N/A

In [89]:
def completes_merge(df1, df2, year):
  merged_df=pd.merge(df1, df2,  on='UNITID',how='inner')

      # Add year as a column
  # merged_df['YEAR'] = year
  merged_df.insert(2,'YEAR',year, True)
  return merged_df

In [90]:
#merging c files with hd institutional info
c2018_2=completes_merge(hd2018, c2018_2,  '2018')
c2019_2=completes_merge( hd2019, c2019_2,  '2019')
c2020_2=completes_merge(hd2020, c2020,  '2020')
c2021_2=completes_merge(hd2021,c2021, '2021')
c2022_2=completes_merge(hd2022, c2022,  '2022')

In [91]:
c2018_2.head()
c2019_2.shape
# c2018_2.columns

(240412, 51)

In [92]:
# c2018.shape #(240794, 51)
# c2019.shape (240412, 51)
#c2020.shape (238689, 51)
# c2021.shape(241826, 51)
# c2022.shape(244004, 51)

In [93]:
combined_completions= pd.concat([c2019_2.reset_index(drop=True),
                                 c2019_2.reset_index(drop=True),
                                   c2020_2.reset_index(drop=True),
                                   c2021_2.reset_index(drop=True),
                                   c2022_2.reset_index(drop=True)])

In [94]:
combined_completions.shape #(1205343,51)

(1205343, 51)

In [97]:
combined_completions.columns

Index(['UNITID', 'INSTNM', 'YEAR', 'IALIAS', 'STABBR', 'OBEREG', 'ICLEVEL',
       'CONTROL', 'DEGGRANT', 'LONGITUD', 'LATITUDE', 'CIPCODE', 'PTOTAL',
       'PTOTALDE', 'PTOTALDES', 'PASSOC', 'PASSOCDE', 'PASSOCDES', 'PBACHL',
       'PBACHLDE', 'PBACHLDES', 'PMASTR', 'PMASTRDE', 'PMASTRDES', 'PDOCRS',
       'PDOCRSDE', 'PDOCRSDES', 'PDOCPP', 'PDOCPPDE', 'PDOCPPDES', 'PDOCOT',
       'PDOCOTDE', 'PDOCOTDES', 'PCERT1A', 'PCERT1ADE', 'PCERT1ADES',
       'PCERT1B', 'PCERT1BDE', 'PCERT1BDES', 'PCERT2', 'PCERT2DE', 'PCERT2DES',
       'PCERT4', 'PCERT4DE', 'PCERT4DES', 'PPBACC', 'PPBACCDE', 'PPBACCDES',
       'PPMAST', 'PPMASTDE', 'PPMASTDES'],
      dtype='object')

In [95]:
# combined_completions.to_csv('depprogramsoffered18_22.csv', index=False)